/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiDeliveriesRouteImport } from './routes/api/deliveries'
import { Route as ApiAddDeliveryRouteImport } from './routes/api/add-delivery'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliveriesRoute = ApiDeliveriesRouteImport.update({
  id: '/api/deliveries',
  path: '/api/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddDeliveryRoute = ApiAddDeliveryRouteImport.update({
  id: '/api/add-delivery',
  path: '/api/add-delivery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/sign-in': typeof SignInRoute
  '/api/add-delivery': typeof ApiAddDeliveryRoute
  '/api/deliveries': typeof ApiDeliveriesRoute
  '/api/session': typeof ApiSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/sign-in': typeof SignInRoute
  '/api/add-delivery': typeof ApiAddDeliveryRoute
  '/api/deliveries': typeof ApiDeliveriesRoute
  '/api/session': typeof ApiSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/sign-in': typeof SignInRoute
  '/api/add-delivery': typeof ApiAddDeliveryRoute
  '/api/deliveries': typeof ApiDeliveriesRoute
  '/api/session': typeof ApiSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/api/add-delivery'
    | '/api/deliveries'
    | '/api/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/sign-in'
    | '/api/add-delivery'
    | '/api/deliveries'
    | '/api/session'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/api/add-delivery'
    | '/api/deliveries'
    | '/api/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  SignInRoute: typeof SignInRoute
  ApiAddDeliveryRoute: typeof ApiAddDeliveryRoute
  ApiDeliveriesRoute: typeof ApiDeliveriesRoute
  ApiSessionRoute: typeof ApiSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deliveries': {
      id: '/api/deliveries'
      path: '/api/deliveries'
      fullPath: '/api/deliveries'
      preLoaderRoute: typeof ApiDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/add-delivery': {
      id: '/api/add-delivery'
      path: '/api/add-delivery'
      fullPath: '/api/add-delivery'
      preLoaderRoute: typeof ApiAddDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  SignInRoute: SignInRoute,
  ApiAddDeliveryRoute: ApiAddDeliveryRoute,
  ApiDeliveriesRoute: ApiDeliveriesRoute,
  ApiSessionRoute: ApiSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
